### ISSUE TITLE
How to move wall during the simulation? 

### ISSUE THREAD

**Issue by ovgeorge** [anders-dc/sphere#13]
Hi here, 
I'm re-implementing my granular gas from granular.jl to sphere. I need confined granular gas with inelastic collisions between particles and energy pumping into the system through movable wall == piston, the explanation can be more clear from the visualization I've obtained from granular.jl  https://www.youtube.com/watch?v=sNwfBtD2IP4

It seems, I cannot setup wall speed as with granular.jl. What should be my course of action, then? 

Also, do I need to disable atmosphere somehow to not lose energy in absence of particle-particle interactions?

**Comment by anders-dc** [comment]
> I'm re-implementing my granular gas from granular.jl to sphere. I need confined granular gas with inelastic collisions between particles and energy pumping into the system through movable wall == piston, the explanation can be more clear from the visualization I've obtained from granular.jl https://www.youtube.com/watch?v=sNwfBtD2IP4
> 
> It seems, I cannot setup wall speed as with granular.jl. What should be my course of action, then?

Take a look at the function [uniaxialStrainRate in sphere.py](https://github.com/anders-dc/sphere/blob/167ae1fe9a881f423cdffd2f3737ce6e9de69f78/python/sphere.py#L3050), which will do exactly what you describe. 

> Also, do I need to disable atmosphere somehow to not lose energy in absence of particle-particle interactions?

In sphere or in Granular.jl? In sphere there is no fluid unless you specifically enable it. With Granular.jl there is no atmosphere if you did not enable it. If you do include it, you can always call `disableAtmosphereDrag!(grain)` for each grain.

**Comment by ovgeorge** [comment]
No not flood with the issues, I'm havin two questions: 
1) Can I use several GPUs installed at the machine simultaneously?

2) I'm running sphere on my node and having some strange error messages:
"Device compute capability value (7.0) not recognized."

[go@gn19 python]$ python shear-test.py 
Warning: Could not find "vtk" python module. Fluid VTK calls will be unavailable
./sphere: processing input file: input/shear-test-init.bin
  Allocating host memory:                         Done
  Reading remaining data from input binary:       Done
  - Number of dimensions: nd = 3
  - Number of particles:  np = 10000
  - Compiled for double precision
  - Timestep length:      time.dt         = 8.44135e-08 s
  - Start at time:        time.current    = 0 s
  - Total sim. time:      time.total      = 5 s
  - File output interval: time.file_dt    = 0.05 s
  - Start at step count:  time.step_count = 0
  - Contact model: Linear-elastic-visco-frictional
  - Using global value for contact stiffness
  - Number of dynamic walls: 0
  - 1st and 2nd dim. boundaries: Periodic
  - Grid: 10 * 10 * 100 cells
  - Domain size: 0.855142 * 0.855142 * 8.55142 m
  - No. of particle bonds: 0
./sphere: processing input file: input/shear-test-init.bin
  Allocating host memory:                         Done
  Reading remaining data from input binary:       Done
  System contains 4 CUDA compatible devices.
Error in cudaCoresPerSM Device compute capability value (7.0) not recognized.  CUDA device ID: 0
  - Name: Tesla V100-SXM2-16GB, compute capability: 7.0.
  - CUDA Driver version: 10.10, runtime version 10.0
Error in cudaCoresPerSM Device compute capability value (7.0) not recognized.  CUDA device ID: 1
  - Name: Tesla V100-SXM2-16GB, compute capability: 7.0.
  - CUDA Driver version: 10.10, runtime version 10.0
Error in cudaCoresPerSM Device compute capability value (7.0) not recognized.  CUDA device ID: 2
  - Name: Tesla V100-SXM2-16GB, compute capability: 7.0.
  - CUDA Driver version: 10.10, runtime version 10.0
Error in cudaCoresPerSM Device compute capability value (7.0) not recognized.  CUDA device ID: 3
  - Name: Tesla V100-SXM2-16GB, compute capability: 7.0.
  - CUDA Driver version: 10.10, runtime version 10.0
  Using CUDA device ID 0 with 0 cores.
  Transfering data to constant device memory:     Done
  Constant values ok (0).
  Allocating global device memory:                Done
  Transfering data to the device:                 Done

  Device memory allocation and transfer complete.
  - Blocks per grid: 40*1*1
  - Threads per block: 256*1*1
  - Shared memory required per block: 1028 bytes

  Entering the main calculation time loop...

  IMPORTANT: Do not close this terminal, doing so will 
             terminate this SPHERE process. Follow the 
             progress by executing:
                $ ./sphere_status shear-test-init

  Current time: 0.00365173/5 s. (10953.7 s_real/s_sim, ETA: 0d 15:12:08)

**Comment by anders-dc** [comment]
I just pushed some changes allowing for compute capability 7.x. Could you please pull the newest commit and try again?

The code only uses a single GPU, and tries to detect the largest one and use that. Otherwise, you can manually select which device to use with the `device` option to the `run` function from the Python API, or, if you launch the `sphere` binary directly from the command line, you can use the `-d <device>` option.

**Comment by ovgeorge** [comment]
I've tested a new version and  problem still persists. Namely, GPU 100% loaded, no updates in command-line interfaces, no updates in sphere_status.
```
[go@gn22 sphere]$ screen -r

  - CUDA Driver version: 10.10, runtime version 10.10
  CUDA device ID: 3
  - Name: Tesla V100-SXM2-16GB, compute capability: 7.0.
  - CUDA Driver version: 10.10, runtime version 10.10
  Using CUDA device ID 0 with 2560 cores.
  Transfering data to constant device memory:     Done
  Constant values ok (0).
  Allocating global device memory:                Done
  Transfering data to the device:                 Done

  Device memory allocation and transfer complete.
  - Blocks per grid: 2*1*1
  - Threads per block: 256*1*1
  - Shared memory required per block: 1028 bytes

  Entering the main calculation time loop...

  IMPORTANT: Do not close this terminal, doing so will
             terminate this SPHERE process. Follow the
             progress by executing:
                $ ./sphere_status gas-test-init

  Current simulation time: 0 s.

```

**Comment by anders-dc** [comment]
Thank you for the update, I have opened issue #14 to address this critical problem. Could you please share your simulation script by email [anders@adamsgaard.dk](mailto:anders@adamsgaard.dk) so I can cross check on different platforms?
